<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AmdHdrScreenshotFixer.Gui\AmdHdrScreenshotFixer.Gui.csproj" />
    <ProjectReference Include="..\AmdHdrScreenshotFixer.Core\AmdHdrScreenshotFixer.Core.csproj" />
  </ItemGroup>
</Project>
