<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>AmdHdrScreenshotFixer.Updater</AssemblyName>
    <RootNamespace>AmdHdrScreenshotFixer.Updater</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AmdHdrScreenshotFixer.Core\AmdHdrScreenshotFixer.Core.csproj" />
  </ItemGroup>
</Project>
